Prepare for core GIF/PNG removal
jenkinsci/scriptler-plugin pull request #47
Opened 2021-12-01 16:06 UTC by NotMyFault

@mtughan Preparation for `https://github.com/jenkinsci/jenkins/pull/5778/files`

Jenkins overrides icons in the order SVG -> PNG -> GIF, therefore modern Jenkins versions will display an SVG if available, older ones a PNG, and even older ones GIFs.

Modern Jenkins:
![](https://i.imgur.com/GXjB3Oa.png)
![](https://i.imgur.com/z7PMG7e.png)

Older Jenkins:
![](https://i.imgur.com/5ykFjVr.png)
![](https://i.imgur.com/IaBhHqN.png)

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

2021-12-02 20:30 UTC, mtughan commented
Thanks @NotMyFault. I'll review this in the next few days and see about getting it merged.

2021-12-22 10:55 UTC, NotMyFault commented
> Thanks @NotMyFault. I'll review this in the next few days and see about getting it merged.

@mtughan Any news about that one 👀 

It would be a charm to get this part released as well.

2021-12-23 19:59 UTC, mtughan requested changes
@NotMyFault, can you make this one small change to make sure all the icons are consistent?

2021-12-23 19:59 UTC, mtughan commented on src/main/resources/org/jenkinsci/plugins/scriptler/ScriptlerManagement/index.jelly
> +										</a>
Please remove the `<a>` element around this icon to be the same as the approval and warning icons. Adding `class="scriptler-icon-slot"` here will result in a `margin-left` of 8px being applied to this element, where it was specifically 0px before.

2021-12-23 20:13 UTC, mtughan approved these changes

2021-12-23 20:13 UTC, merged

2021-12-23 20:53 UTC, NotMyFault commented
Thanks for merging, will add it to my list at the core PR in a bit 👏🏻

2021-12-28 14:22 UTC, NotMyFault commented
@mtughan Thanks for merging, can you release this please?
Thanks in advance!

2022-01-06 23:23 UTC, NotMyFault commented
I see you published a new release to GitHub, but that does not trigger a release published to the [Artifactory](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/scriptler/). It's still stuck on a release from November 2021.
Depending on your setup, you either need to use the maven release plugin or publish via CD.

2022-03-12 04:22 UTC, mtughan commented
Yeah, I need to release a new version. The new release published to GitHub was just adding a proper release note for a security fix; the version had already been previously released. I'm hoping to get another PR or two in before I perform the release, plus look into enabling CD at some point.

2022-04-14 06:55 UTC, NotMyFault commented
The next LTS baseline selection is coming up very soon, which includes the icon removal from core. Could you please trigger a release of this plugin before, to prepare it for the removal? @mtughan

2022-05-08 19:34 UTC, mtughan commented
> The next LTS baseline selection is coming up very soon, which includes the icon removal from core. Could you please trigger a release of this plugin before, to prepare it for the removal? @mtughan

Scriptler 3.5 is released with this fix and a few others.