Refresh UI
jenkinsci/scriptler-plugin pull request #59
Opened 2023-05-24 08:09 UTC by timja

Unblocks https://github.com/jenkinsci/jenkins/pull/7717
Test issue is in https://github.com/jenkinsci/acceptance-test-harness/pull/1189

Changes:
- Removed icons from headings. see guidance at: https://weekly.ci.jenkins.io/design-library/Symbols/
- Used built-in controls rather than custom html. This is what is blocking the core PR as it doesn't adapt to new markup in the controls.
- Incrementalise the plugin to make testing PRs across components simple
- Refreshed pom to latest standards from the [archetypes](https://github.com/jenkinsci/archetypes)
- Changed legacy tango icons to [symbols](https://weekly.ci.jenkins.io/design-library/Symbols/). <- Not done on the run/edit scripts page but done everywhere else I think
- Removed no longer needed tables to divs compatibility (p:blockWrapper)
- Changed Submit to Save in a few places
- Put the Scripter management link in the configuration category so it no longer shows up in 'uncategorized'

<img width="984" alt="image" src="https://github.com/jenkinsci/scriptler-plugin/assets/21194782/edd61ed9-225a-4e35-9e6e-152aa4abb49b">

<img width="1428" alt="image" src="https://github.com/jenkinsci/scriptler-plugin/assets/21194782/6dad8e49-9b0d-407b-a411-30f804de1335">

### Testing done

Clicked through UI and saved and edited scripts

### Submitter checklist

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-06-01 15:24 UTC, mtughan requested changes
Looks generally fine, but I will do some testing with these changes before merging it. There's also the one comment I have below.

2023-06-01 15:24 UTC, mtughan commented on src/main/resources/org/jenkinsci/plugins/scriptler/ScriptlerManagement/scriptSettings.properties
> +RestrictionDescription = Script is always executed on the controllerMaster
I think you meant to get rid of the term "master" here?
```suggestion
RestrictionDescription = Script is always executed on the controller
```

2023-06-01 15:55 UTC, timja commented on pom.xml
> +		<version>4.64</version>
```suggestion
		<version>4.65</version>
```

2023-06-01 15:55 UTC, timja commented on Jenkinsfile
> +    [platform: 'linux', jdk: '17'],
```suggestion
    [platform: 'linux', jdk: '17'],
    [platform: 'windows', jdk: '11']
```

2023-06-01 16:14 UTC, timja commented
(I've re-enabled Windows builds, turned out to be a general regression affecting a few repositories and has been fixed in the test harness)

2023-06-01 16:41 UTC, mtughan submitted a review, later dismissed
Thanks @timja, changes look good from my side then. Will try to test this in the next few days and merge if all looks good.

2023-06-06 12:59 UTC, mtughan commented
@timja, I rebased this PR as it conflicted with #60. Can you double-check that all looks good from your side with it?

2023-06-06 13:46 UTC, timja commented
> @timja, I rebased this PR as it conflicted with #60. Can you double-check that all looks good from your side with it?

Merge LGTM

2023-06-16 06:45 UTC, timja commented
@mtughan anything you are waiting on here?

2023-06-16 17:25 UTC, mtughan approved these changes
@timja, just on me to have time to review it. I just finished up a task I've been working on for the past 2 weeks, so I'm going to work on cleaning up a bunch of outstanding tasks on the plugin.

2023-06-16 17:25 UTC, merged