[JENKINS-71015] Re-Support Job DSL
jenkinsci/scriptler-plugin pull request #80
Opened 2023-10-01 11:56 UTC by limejuny

### Detail

 - After active-choices-plugin 2.6.0, it use `ScriptlerBuilder` instead of `scriptlerScriptId` and `parameter`. But `ScriptlerBuilder` doesn't have `DataBoundConstructor` annotation, so Job DSL can't recognize the scriptler script syntax in `cascadeChoiceParameter`.
 - Before 2.5.7
   - ![image](https://github.com/biouno/uno-choice-plugin/assets/16630665/3ed374fd-5744-4f3c-b567-aa6fedad0450)
   - ```
     scriptlerScript {
       scriptlerScriptId(String value)
       parameters {
         scriptlerScriptParameter {
           name(String value)
         }
       }
     }
     ```
 - After 2.6.0
   - ![image](https://github.com/biouno/uno-choice-plugin/assets/16630665/cec02a53-486f-424b-bebe-c25977c1a46a)
 - After this commit
   - ![image](https://github.com/biouno/uno-choice-plugin/assets/16630665/0011bbb8-ffec-49b4-88a9-ecbd58fe13d7)
   - ```
     scriptlerScript {
       scriptlerBuilder {
         buildersId(String value)
         scriptId(String value)
         propagateParams(boolean value)
         defineParams {
           parameters {
             parameter {
               name(String value)
               value(String value)
             }
           }
         }
       }
       isSandboxed(Boolean value)
       scriptlerScriptId(String value)
     }
     ```

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-10-03 12:30 UTC, mtughan requested changes

2023-10-03 12:53 UTC, limejuny commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
Yes, I think it is more complicated, too...
But I found the `definedParams` in other json file or test code.

I didn't deep dive other part of codes, so I don't know why is the `definedParams` exists, and I want to change as small as possible.
So I created new constructor of `ScriptlerBuilder`.

Here is some examples.

---
![image](https://github.com/jenkinsci/scriptler-plugin/assets/16630665/38e90119-732b-4b59-ae29-834049400893)
---
![image](https://github.com/jenkinsci/scriptler-plugin/assets/16630665/ebf93fc6-6bb1-48a8-9c78-a46353f74799)

2023-10-03 16:14 UTC, mtughan commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
No worries. I would take it out, as this `defineParams` key is only used in the REST communication between the Jelly in the UI and the backend. Long-term, I would probably like to get rid of it, and there's no reason to introduce its usage into a user-facing part of the code (which the Job DSL is).

2023-10-03 16:20 UTC, limejuny commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
OK, Thanks. I'll test again without `defineParams`.

2023-10-03 16:35 UTC, limejuny commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
It works with this script, thanks!

---
![image](https://github.com/jenkinsci/scriptler-plugin/assets/16630665/6a90497c-2dee-439b-94b1-cb784fe67282)
---
![image](https://github.com/jenkinsci/scriptler-plugin/assets/16630665/e920b056-3f71-4f71-a591-2e9a27252ef8)

2023-10-03 18:01 UTC, mtughan requested changes
The code diff looks good now, but the commit message still shows the outdated `defineParams` syntax. Can you clean that up as well? Would also be helpful to fix the PR description to match.

2023-10-03 18:02 UTC, mtughan commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
Label added. :)

2023-10-04 00:04 UTC, limejuny commented on src/main/java/org/jenkinsci/plugins/scriptler/builder/ScriptlerBuilder.java
> +    @DataBoundConstructor
Thanks!

2023-10-04 00:06 UTC, limejuny commented
> The code diff looks good now, but the commit message still shows the outdated `defineParams` syntax. Can you clean that up as well? Would also be helpful to fix the PR description to match.

Oh, Thank you for the good point.

2023-10-04 13:08 UTC, mtughan approved these changes

2023-10-18 13:10 UTC, merged

2023-10-18 13:11 UTC, mtughan commented
Oops, sorry for the delay on this one, @limejuny! I was waiting for the checks to pass and it slipped my notice afterwards.